# indentation is very important for yml file incorrectly done will not work
# every container has image(s) for it to run
version: "3" #this is docker version is not app version
services:
  apache: # apache server
    container_name: for_web_tutorial
    build: . # build from Docker file not from image
    ports:
      - 8800:88 #ex:in
      - 8811:8080
    volumes:
      # - ./js_src/:/
      - ./php_src:/app
      - ./libs/apache:/etc/apache2/
      - ./libs/apache:/var/log/apache2/
    tty: true
    links: 
      - database
    environment:
      - TZ=Asia/Phnom_Penh`
    # restart: always # this is to start container when docker start / or computer reboot
  database: 
      container_name: tutorial_db
      image: "mysql:5"
      ports:
        - 3308:3306
      volumes:
      # need to make file sharing in docker filesharing preference to get it to work.
        - ./mysql/data:/etc/mysql/conf.d # working-directory : mysql server directory in container
        - ./mysql/data:/var/lib/mysql #ex/in
      environment:
        MYSQL_DATABASE: kasekordb
        MYSQL_ROOT_PASSWORD: 123456 # if need to chage dont chage it here after build need to chage in mysql / phpmyadmin
        MYSQL_USER: seksitha
        MYSQL_USER_PASSWORD: 123456
        MYSQL_ROOT_HOST: "%"
        MYSQL_USER_HOST: "%"